#ifndef PEACHY_COMPARISONTYPE_H
#define PEACHY_COMPARISONTYPE_H

namespace peachy {

  enum ComparisonType {
    COMPARISON_EQUAL,
    COMPARISON_LESS_THAN,
    COMPARISON_LESS_THAN_OR_EQUAL,
    COMPARISON_GREATER_THAN,
    COMPARISON_GREATER_THAN_OR_EQUAL,
    COMPARISON_NONE,
    COMPARISON_NOT_EQUAL
  };
}

#endif
