#ifndef PEACHY_EXPRESSIONTYPE_H
#define PEACHY_EXPRESSIONTYPE_H

namespace peachy {

  enum ExpressionType {
    EXPRESSION_ASSIGNMENT,
    EXPRESSION_QUIT,
    EXPRESSION_STRING_LITERAL,
    EXPRESSION_UNKNOWN
  };
}

#endif
