#ifndef PEACHY_TOKENTYPE_H
#define PEACHY_TOKENTYPE_H

namespace peachy {

  enum TokenType {
    TOKEN_COMMENT_LINE,
    TOKEN_EMPTY,
    TOKEN_EOF,
    TOKEN_IDENTIFIER,
    TOKEN_INTEGER,
    TOKEN_KEYWORD,
    TOKEN_LEFT_BRACE,
    TOKEN_LEFT_BRACKET,
    TOKEN_LEFT_PARENTHESIS,
    TOKEN_NEWLINE,
    TOKEN_NUMBER,
    TOKEN_OPERATOR,
    TOKEN_RIGHT_BRACE,
    TOKEN_RIGHT_BRACKET,
    TOKEN_RIGHT_PARENTHESIS,
    TOKEN_STRING
  };
}

#endif
